# Generated by Django 3.2.9 on 2023-01-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.PositiveBigIntegerField(default=1, null=True)),
                ('max_temp', models.IntegerField(null=True)),
                ('min_temp', models.IntegerField(null=True)),
                ('humidity', models.PositiveBigIntegerField(null=True)),
                ('rainfall', models.PositiveBigIntegerField(null=True)),
                ('precipitation', models.PositiveBigIntegerField(null=True)),
                ('fishing', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')])),
                ('results', models.CharField(blank=True, max_length=10, null=True)),
                ('accuracy', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
