# Generated by Django 3.2.9 on 2023-01-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='population',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
