# Generated by Django 3.2.9 on 2023-01-16 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20230116_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='county',
        ),
    ]
