# Generated by Django 3.2.9 on 2023-01-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_data_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='fishing',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')]),
        ),
    ]
