# Generated by Django 3.2.9 on 2023-01-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_alter_data_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='accuracy',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
