# Generated by Django 3.2.9 on 2023-01-27 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0009_alter_data_county'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='county',
        ),
    ]
