# Generated by Django 3.2.9 on 2023-01-04 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='profile_updated',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='profile_updated',
        ),
    ]
