# Generated by Django 3.2.9 on 2023-01-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('job_desc', models.TextField()),
                ('budget', models.FloatField()),
                ('vacancy', models.PositiveIntegerField(default=1, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('qualifications', models.TextField(null=True)),
                ('company_details', models.TextField(null=True)),
                ('terms_of_service', models.CharField(choices=[('Contract', 'Contract'), ('Temporary', 'Temporary'), ('Permanent', 'Permanent')], max_length=100, null=True)),
                ('dateline', models.DateField(null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('terms_and_conditions', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='jobrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal', models.TextField()),
                ('experience', models.CharField(choices=[('less than 1(yr)', 'less than 1(yr)'), ('1-2 (yrs)', '1-2 (yrs)'), ('3-4 (yrs)', '3-4 (yrs)'), ('Above 5yrs', 'Above 5yrs')], max_length=100, null=True)),
                ('your_budget', models.FloatField()),
            ],
        ),
    ]
