# Generated by Django 3.2.9 on 2023-01-03 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='applicant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.applicant'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
        migrations.AddField(
            model_name='job',
            name='area_of_specialization',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.areaofspecialization'),
        ),
        migrations.AddField(
            model_name='job',
            name='employer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.employer'),
        ),
    ]
