# Generated by Django 3.2.9 on 2023-01-04 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='jobrequest',
            name='applicant',
        ),
    ]
