# Generated by Django 3.2.9 on 2023-01-04 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20230104_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='area_of_specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.areaofspecialization'),
        ),
    ]
