# Generated by Django 3.2.9 on 2023-01-04 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_jobrequest_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobrequest',
            old_name='job',
            new_name='job_category',
        ),
    ]
