# Generated by Django 3.2.9 on 2023-01-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_rename_job_jobrequest_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='job_category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
