# Generated by Django 3.2.9 on 2023-01-04 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230104_1444'),
        ('jobs', '0008_rename_job_category_jobrequest_job_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrequest',
            name='job_name',
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.applicant'),
        ),
    ]
