# Generated by Django 3.2.9 on 2023-01-04 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20230104_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jobs.job'),
        ),
    ]
