# Generated by Django 3.2.9 on 2023-01-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20230104_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobrequest',
            old_name='job',
            new_name='job_name',
        ),
    ]
