# Generated by Django 3.2.9 on 2023-01-04 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_rename_job_jobrequest_job_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='job_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
    ]
