# Generated by Django 3.2.9 on 2023-01-04 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_jobrequest_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobrequest',
            old_name='job_name',
            new_name='job',
        ),
    ]
