# Generated by Django 3.2.9 on 2023-01-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_rename_job_name_jobrequest_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_website',
            field=models.URLField(null=True),
        ),
    ]
