# Generated by Django 3.2.9 on 2023-01-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_alter_jobrequest_your_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='support_document',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
